version: "2"

services:
  zeitgitter-dev:
    restart: unless-stopped
    image: zeitgitter-dev
    build: ./zeitgitter-dev
    container_name: zeitgitter-dev
    env_file:
      - "server.env"
      - "dev.env"
    ports:
      - 15176:15177
    volumes:
      - ./persistent-data-dev:/persistent-data
