version: "2"

services:
  autoblockchainify:
    restart: unless-stopped
    image: zeitgitter/autoblockchainify
    build: ./autoblockchainify
    container_name: autoblockchainify
    env_file:
      - "server.env"
    volumes:
      - /wherever/your/data/is:/blockchain
